### ISSUE TITLE
Close from inside the popup controller 

### ISSUE THREAD

**Issue by jaiversin** [cezarywojcik/CWPopup#1]
Hi, 

Is there a way to dismiss the popup view from the presented view controller?

Thanks.

**Comment by MJACOBS84** [comment]
[self.parentViewController dismissPopupViewControllerAnimated:YES completion:^{
                NSLog(@"popup view dismissed");
            }];

call this on your popup view controller
;)

**Comment by seandeng** [comment]
thanks MJACOBS84 , it works for me  :+1:
