### ISSUE TITLE
1.2.5 Podspec

### ISSUE THREAD

**Issue by tbowers** [cezarywojcik/CWPopup#22]
It would appear the 1.2.5 podspec is broke.

https://github.com/CocoaPods/CocoaPods/issues/2867

**Comment by LucasVidal** [comment]
Can the author please push the fixed specs to cocoapods?
The invalid flag is still there 
https://github.com/CocoaPods/Specs/blob/4a2a7d017cddfdec782da5bbdd2abee353549280/Specs/CWPopup/1.2.5/CWPopup.podspec.json

Thanks!

**Comment by Dids** [comment]
+1

As a workaround though, this works:
```ruby
pod 'CWPopup', :git => 'http://github.com/cezarywojcik/CWPopup.git'
```

**Comment by LucasVidal** [comment]
Yes, I was just about to do that. Thanks!

**Comment by cezarywojcik** [comment]
Sorry for taking so long to update this; I've been a bit busy.

I pushed a new 1.2.6 spec to CocoaPods that removes the typo.
