### ISSUE TITLE
Weird behaviour while adding onto a UITableViewController

### ISSUE THREAD

**Issue by genaks** [cezarywojcik/CWPopup#32]
While trying to add the popup to a UITableViewController, the pop up view continues to scroll along with the TableView's scrollView and only a part of the tableViewController's view is dark. Maybe I am doing it the wrong way but here it is - 

```
[self presentPopupViewController:someViewController animated:YES completion:^{
}];
```

**Comment by cezarywojcik** [comment]
This popup gets added as a subview to the current view controller. In a table view controller, the `view` is a `tableView`, which is a `scrollView`. 

Two workarounds:
1. Disable scrolling when popup is presented
2. Embed your `UITableViewController` in a `UIViewController` (this can be helpful for other reasons as well)
